### ISSUE TITLE
Investigate which ORM to use for backend (SERVER)

### ISSUE THREAD

**Issue by andram11** [chingu-voyages/v49-tier3-team-26#28]
**__Task Description__**
Investigate which ORM (Knex Js, Sequelize, TypeORM etc) is appropriate for our backend. 

**__Technical Considerations__**
It should be compatible with Node Js.
It should have support for Postgres. 

**__Additional Considerations__**
A branch is not needed for this.

**Comment by Morais-C** [comment]
Prisma  - https://www.prisma.io/ - is being tested.

If team approve it, this issue can be closed.
