### ISSUE TITLE
Set-up ORM connexion (SERVER)

### ISSUE THREAD

**Issue by andram11** [chingu-voyages/v49-tier3-team-26#29]
**__Task Description__**
Once an ORM solution has been chosen, set up the library connexion, datamodel, database to the Postgres database.

**__Technical Considerations__**
Include any connexion secrets in the Github secrets section.

**__Additional Considerations__**
A branch should be created for this one.

**Comment by Morais-C** [comment]
We decided to try Prisma.
(https://www.prisma.io/)
